### ISSUE TITLE
Missing changelog for 2.0.0 on Hackage

### ISSUE THREAD

**Issue by andreasabel** [haskell/os-string#10]
<img width="675" alt="Screenshot 2023-12-14 at 18 13 44" src="https://github.com/haskell/os-string/assets/1155218/96f5ee76-d29b-47e8-b7c2-abce8c3ccb56">

Maybe the ??? is also worth fixing.

**Comment by hasufell** [comment]
Changelog is not metadata and can't be retroactively fixed. The next release will show a better changelog.

**Comment by hasufell** [comment]
https://hackage.haskell.org/package/os-string-2.0.1/changelog
