### ISSUE TITLE
Prohibit using of incompatible windows encodings in `encodeWith`?

### ISSUE THREAD

**Issue by hasufell** [haskell/os-string#15]
We provide:

https://github.com/haskell/os-string/blob/82fb474812f769e5ca8f25520400ba85f56c97c4/System/OsString/Internal.hs#L58-L67

However, we expect `WindowsString` to be wide char (UTF-16 or UCS-2 or anything else that is wide char compatible). Otherwise, a lot of functions will simply crash, e.g.:

https://github.com/haskell/os-string/blob/82fb474812f769e5ca8f25520400ba85f56c97c4/System/OsString/Data/ByteString/Short/Word16.hs#L326-L327

and

https://github.com/haskell/os-string/blob/82fb474812f769e5ca8f25520400ba85f56c97c4/System/OsString/Data/ByteString/Short/Internal.hs#L417-L420

----

Possible solutions:

- just document this expectation
- test the byte array for wide char compliance and throw `Left` otherwise (this is my favorite one... doesn't change API and is rather flexible)
- use a more restricted sum type instead of `TextEncoding` for windows to only allow e.g. UCS-2 and UTF-16 and other known wide char encodings
- remove the windows TextEncoding and assume UTF-16

We certainly cannot support both char and wide-char formats on windows, because that doesn't make sense, given that our Win32 API expects wide chars. We usually expect that strings come from operating system API (e.g. Win32 package), but of course the users needs a way to construct them manually as well. It seems like an unnecessary footgun, however.

@Bodigrim opinions?

**Comment by Bodigrim** [comment]
I'd probably just document that using non-wide-char encodings for `winEnc` is a very bad idea. In future, when there is another reason for a major release, one can do (3) or (4).
