### ISSUE TITLE
length function is confusing

### ISSUE THREAD

**Issue by BurningWitness** [haskell/os-string#17]
Under Windows `length` appears to refer to the number of underlying bytes instead of the number of 16-bit codepoints, which is at odds with the rest of the API (and other libraries, e.g. `text`). `numWord`, even though it is present in the `Short.Word16` module, is not exposed in a cross-platform fashion.

**Comment by hasufell** [comment]
What function are you referring to exactly?

**Comment by hasufell** [comment]
You are right: https://hackage.haskell.org/package/os-string-2.0.2.2/docs/System-OsString.html#v:length

All functionss in OsString under windows deal with Word16 boundaries. Length should too.

**Comment by hasufell** [comment]
Released as https://hackage.haskell.org/package/os-string-2.0.3

**Comment by BurningWitness** [comment]
Since this directly changes the behavior of the `length` function, shouldn't this have been a major version bump?

**Comment by hasufell** [comment]
How so? PVP doesn't specify what to do on behavior changes.

**Comment by BurningWitness** [comment]
The decision tree on the [website](https://pvp.haskell.org/) has "Did the behavior of any exported functions change?" as one of the questions.

**Comment by hasufell** [comment]
The decision tree is irrelevant. Please refer to the actual specification text.

For more information see:

* https://github.com/haskell/pvp/issues/10
* https://github.com/haskell/pvp/issues/55

**Comment by BurningWitness** [comment]
I would simply argue here that since you're obviously changing what `length` does this is a breaking change (and thus requires a major version bump). I argue for this even knowing that the documentation on the function is quite ambiguous (after all "length" could have always referred to the number of underlying code points and everyone using it could've assumed it to work that way, but never tested under Windows).

This is however not a "please refer to the actual specification text" matter, as the pvp#55 issue you've linked is specifically a discussion of what the spirit of the PVP is. As such there is no agreement on the matter and whether or not to consider the change breaking is currently merely maintainer preference.

**Comment by hasufell** [comment]
Thanks for your input.
