### ISSUE TITLE
`encodeUtf` and `decodeUtf` incorrectly catch asynchronous exceptions

### ISSUE THREAD

**Issue by wz1000** [haskell/os-string#22]
`encodeWith` and `decodeWith` use `try @SomeException` to catch all exceptions that may arise while dealing with C buffers.

See for instance https://github.com/haskell/os-string/blob/06a9edc5d25191f658407786d9d964e34d09755f/System/OsString/Common.hs#L239

This is incorrect, as asynchronous exceptions thrown to such code (for instance using `killThread` or `^C`) should not result in a `EncodingException`.

The simplest way to fix it is to see if the exception is `SomeAsyncException` and if so reraise it.

See also https://gitlab.haskell.org/ghc/ghc/-/issues/25479

**Comment by hasufell** [comment]
Can you provide a PR?

**Comment by hasufell** [comment]
* https://github.com/haskell/os-string/pull/24
* https://github.com/haskell/filepath/pull/238
* https://github.com/haskell/filepath/pull/239
* https://github.com/haskell/filepath/pull/240

**Comment by hasufell** [comment]
* https://hackage.haskell.org/package/os-string-2.0.7
* https://github.com/haskell/os-string/releases/tag/v2.0.7
