### ISSUE TITLE
Provide coercions between OsString and WindowsString / PosixString

### ISSUE THREAD

**Issue by Bodigrim** [haskell/os-string#4]
It would be nice to have something like
```haskell
import Data.Type.Coercion

coercionToPosixString :: Maybe (Coercion OsString PosixString)
#if defined(mingw32_HOST_OS)
coercionToPosixString = Nothing 
#else
coercionToPosixString = Just Coercion
#endif
```
and same for `coercionToWindowsString :: Maybe (Coercion OsString WindowsString)`

Names are inspired by `aeson`: [`coercionToHashMap`](https://hackage.haskell.org/package/aeson-2.2.1.0/docs/Data-Aeson-KeyMap.html#v:coercionToHashMap) and [`coercionToMap`](https://hackage.haskell.org/package/aeson-2.2.1.0/docs/Data-Aeson-KeyMap.html#v:coercionToMap).

**Comment by Bodigrim** [comment]
And same for `OsChar` / `PosixChar` / `WindowsChar`.

**Comment by Bodigrim** [comment]
Even better would be to provide both coercions at the same time:
```
coercionToPosix :: Maybe (Coercion OsChar OsString, Coercion OsString PosixString)
coercionToWindows :: Maybe (Coercion OsChar WindowsString, Coercion OsString WindowsString)
```

**Comment by hasufell** [comment]
What exactly are the semantics? Do we encode/decode? Is that really coercion?

**Comment by hasufell** [comment]
So coercion from OsString to PosixString just fails on windows?

I'm not too familiar with that mechanism.

**Comment by hasufell** [comment]
Can you provide a PR?
