### ISSUE TITLE
Provide laxEncodeUtf :: String -> {Os,Posix,Windows}String, replacing surrogates

### ISSUE THREAD

**Issue by Bodigrim** [haskell/os-string#5]
(If this goes against the design principles of `os-string`, feel free to dismiss)

1. `encodeUtf` currently says that it's partial and can throw an exception. When exactly is it the case? If it's only for `Char`s from [`Surrogate`](https://hackage.haskell.org/package/base-4.16.3.0/docs/Data-Char.html#v:Surrogate) category, it would be nice to document it explicitly.

2. If it's only for surrogates, would it be possible to provide a function `laxEncodeUtf :: String -> {Os,Posix,Windows}String` which behaves [same as `text` package](https://hackage.haskell.org/package/text-2.1/docs/Data-Text.html#g:2) does, replacing surrogates with ["�" (U+FFFD)](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character)?

I understand the desire to be explicit and unforgiving, but in my personal experience the lack of `String -> OsString` is very discouraging. If replacing surrogates with � works good enough for `text` all these years, it might be not too bad to follow the suite.

**Comment by hasufell** [comment]
You can already do that:

```hs
import Data.Either (either)
import GHC.IO.Encoding.UTF8 (mkUTF8)
import GHC.IO.Encoding.Failure (CodingFailureMode(..))
import System.OsString.Posix (encodeWith)

laxEncodeUtf :: String -> PosixString
laxEncodeUtf = either (fail . show) id . encodeWith (mkUTF8 TransliterateCodingFailure)
```

This mechanism is already used for showing error messages in unix afair.

But yeah, I'm not sure this should be part of proper API.

> When exactly is it the case? If it's only for Chars from Surrogate category, it would be nice to document it explicitly.

I think so.

**Comment by hasufell** [comment]
I think you don't like `MonadThrow` 😅

**Comment by hasufell** [comment]
For reference: https://github.com/haskell/filepath/blob/69141cb9c3b70bbbb9877d36be8a896ac6897596/tests/abstract-filepath/EncodingSpec.hs#L67-L76

```hs
  , ("utf-8 roundtrip encode cannot deal with some surrogates",
     property $
      let str = [toEnum 0xDFF0, toEnum 0xDFF2]
          encoded = encodeWithTE (mkUTF8 RoundtripFailure) str
          decoded = decodeWithTE (mkUTF8 RoundtripFailure) =<< encoded
      in decoded === Left (EncodingError ("recoverEncode: invalid argument (cannot encode character " <> show (head str) <> ")") Nothing))
```

**Comment by hasufell** [comment]
I'm rather -1 towards replacing things from the input with random other chars. I'm fine however with a function crashing on invalid input. If the user has a smart constructor or other things, this can work ok: https://github.com/haskell/os-string/pull/7

Crashing is better than attempting to run file operations on filepaths we just conjured up.
